CREATE TABLE IF NOT EXISTS examples(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  description text,
  deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS task(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  done BOOLEAN,
  examplesId INTEGER REFERENCES examples(id)
);

-- INSERT example data --
INSERT INTO examples(name, description, deliverydate)
  VALUES ('Project Clone Dana', 'Using express and react native', '2019-11-23');

-- INSERT task data --
INSERT INTO task(name, done, examplesId)
  VALUES ('Login api', false, 1);