CREATE TABLE IF NOT EXISTS examples(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  description text,
  deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS news(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  icon text NOT NULL,
  title text NOT NULL CHECK (title <> ''),
  name text NOT NULL CHECK (name <> ''),
  image text,
  description text NOT NULL
);

CREATE TABLE IF NOT EXISTS task(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  done BOOLEAN,
  examplesId INTEGER REFERENCES examples(id)
);

CREATE TABLE IF NOT EXISTS vouchers(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  nominal INTEGER NOT NULL,
  created_at date NOT NULL,
  expired_at date NOT NULL
);

-- INSERT example data --
INSERT INTO examples(name, description, deliverydate)
  VALUES ('Project Clone Dana', 'Using express and react native', '2019-11-23');

-- INSERT task data --
INSERT INTO task(name, done, examplesId)
  VALUES ('Login api', false, 1);

  ALTER TABLE vouchers ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'